[build]
command = "cd ../.. && pnpm install && pnpm build --filter sb"
publish = ".output"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../../packages/ui ../../packages/tailwind-config ../../packages/pinia-store"

[context.deploy-preview.environment]
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
